### PR TITLE
Fix GHC 8.4

### PR DESCRIPTION
**Pull request by k-bx**

### CODE REVIEW

**Comment by k-bx** [comment]
A Hackage release would be much appreciated. If needed, I am happy to do the Hackage/Stackage/Travis maintainment. Thanks!

**Comment by odanoburu** [comment]
@k-bx thanks for the PR!

I was deferring putting the package on hackage because some of its modules are pretty bad atm. however, some parts are more stable (like the parse-print part), so maybe I should split the library and put the parsing-printing code there. what do you think? (or are using other parts of the library too?)

**Comment by k-bx** [comment]
I don't have any preference really. All my usage so far is in https://github.com/k-bx/nlp-trainer/blob/master/ud-conll-extractor/src/Main.hs , but I expect to work with the lib more heavily later.

**Comment by k-bx** [comment]
> ID: Word index, integer starting at 1 for each new sentence; may be a range for multiword tokens; may be a decimal number for empty nodes.

http://universaldependencies.org/format.html

**Pull request merged**
