### PR TITLE
fixed errors with new version of mergaparsec

### PR DESCRIPTION
**Pull request by arademaker**
The lib now builds with lts-17.2. It means dependencies are 

```
 
  build-depends:       base >=4.9 && <5,
                       containers >0.5.8 && <0.7,
                       directory ==1.3.*,
                       filepath ==1.4.*,
                       megaparsec ==9.*,
                       void <1
``` 

I tried to follow the code style as close as possible. But I show to import Text.Megaparsec with `qualified` option adopting the prefix TM.  

I didn't understand yet what the comments starting with `-- |` means. Maybe a kind of docstring? For instance:

```haskell
---
-- conllu parsers
rawSents :: Parser (RawData String Void)
-- | parse CoNLL-U sentences with recovery.
rawSents = rawSentsC sentence
```

The `---` is a section? Why the comment need to be between the type signature and the implementation?

### CODE REVIEW

**Comment by odanoburu** [comment]
> I didn't understand yet what the comments starting with -- | means. Maybe a kind of docstring? 

yes, these comments are Haddock markup, which is used to build Haskell documentation [as seen on hackage](http://hackage.haskell.org/package/hs-conllu-0.1.2/docs/Conllu-Parse.html)! you can read more about it [here](https://haskell-haddock.readthedocs.io/en/latest/markup.html) or [here](https://kowainik.github.io/posts/haddock-tips).

overall the PR seems fine! I had never used Haskell testing libraries when writing this code so hs-conllu has no tests. can you confirm it seems to work by trying the CLI commands on large corpora?

**Comment by arademaker** [comment]
I tested with few files from the http://github.com/universaldependencies/UD_Portuguese-Bosque. Now I am trying to simplify and make the `.travis.yaml` works with stack.

**Comment by arademaker** [comment]
Ok Travis is passing. I have basically copied the minimal .travis.yaml file suggested in the stack documentation.

**Comment by arademaker** [comment]
in this last commit, I used the @odanoburu solution for solving the `Ord ID` bug. But this commit does not produce any warnings and the current version in the branch `bump versions produces a lot of warnings.

**Pull request closed without merging**
